{% set name = "fegrow" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cole-group/FEgrow/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c805f828857f351bd1bd311749e2d0836c93f6433ed37b5bfb0e900cc4a6b011

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python >=3.8, <3.11
    - pip
  run:
    - python >=3.8, <3.11
    - openmmforcefields >=0.9.0
    - openbabel
    - rdkit
    - mols2grid >=0.2.4
    - openff-toolkit >=0.11
    - parmed
    - openmm >=7.5.0
    - openmm-ml
    - typing-extensions
    - pdbfixer >=1.8.0
    - tqdm
    - torchani >2.2.0
    - openmm-torch >=0.8
    - pytorch-gpu >=1.10.0
    - py3dmol
    - prody >=2.0.2
    - pint

test:
  imports:
    - fegrow
  requires:
    - pip
    - pytest
  commands:
    - python -c "import pytest; from fegrow.testing import loc ; pytest.main([loc])"

about:
  home: https://cole-group.github.io/FEgrow/
  summary: 'FEgrow: generate congeneric ligands for FEP by growing a template molecule.'
  description: |
    FEgrow is an interactive workflow for building user-defined 
    congeneric series of ligands in protein binding pockets 
    for input to free energy calculations.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://cole-group.github.io/FEgrow/
  dev_url: https://github.com/cole-group/FEgrow

extra:
  recipe-maintainers:
    - bieniekmateusz
