{% set name = "fegrow" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cole-group/FEgrow/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dee11748896ad2da696aeb11f7baaccc131ef06a2821f083ac91f93d3de1d5c1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - openmm-torch >=0.7
    - openmmforcefields >=0.9.0
    - openbabel
    - rdkit
    - mols2grid >=0.2.4
    - openff-toolkit-base >=0.10.0, <0.11
    - parmed
    - openmm >=7.5.0
    - typing-extensions
    - pdbfixer
    - tqdm
    - torchani
    - py3dmol
    - prody >=2.0.2

test:
  imports:
    - fegrow
  requires:
    - pip
    - pytest
  commands:
    - python -c "import pytest; from fegrow.testing import loc ; pytest.main([loc])"

about:
  home: https://cole-group.github.io/FEgrow/
  summary: 'FEgrow: generate congeneric ligands for FEP by growing a template molecule.'
  description: |
    FEgrow is an interactive workflow for building user-defined 
    congeneric series of ligands in protein binding pockets 
    for input to free energy calculations.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://cole-group.github.io/FEgrow/
  dev_url: https://github.com/cole-group/FEgrow

extra:
  recipe-maintainers:
    - bieniekmateusz
